/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MockDB_CONSTANTS_H
#define MockDB_CONSTANTS_H

#include "MockDB_types.h"

namespace MockDBServer {

class MockDBConstants {
 public:
  MockDBConstants();

};

extern const MockDBConstants g_MockDB_constants;

} // namespace

#endif
