/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MockDB_constants.h"

namespace MockDBServer {

const MockDBConstants g_MockDB_constants;

MockDBConstants::MockDBConstants() {
}

} // namespace

