/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BackupServer_CONSTANTS_H
#define BackupServer_CONSTANTS_H

#include "BackupServer_types.h"

namespace BackupServer {

class BackupServerConstants {
 public:
  BackupServerConstants();

};

extern const BackupServerConstants g_BackupServer_constants;

} // namespace

#endif
