/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "BackupServer_constants.h"

namespace BackupServer {

const BackupServerConstants g_BackupServer_constants;

BackupServerConstants::BackupServerConstants() {
}

} // namespace

